apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-deployment
  labels:
    app: gowebapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowebapp-label
  template:
    metadata:
      labels:
        app: gowebapp-label
    spec:
      containers:
        - name: gowebapp-cont
          image: truebad0ur/gowebapp:v3
          ports:
            - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: nodeport-gowebapp-service 
spec: 
  type: NodePort
  selector:
    app: gowebapp-label

  ports:
    - nodePort: 31337
      port: 8080 
      targetPort: 8080