apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-deployment
  labels:
    app: gowebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gowebapp
  template:
    metadata:
      labels:
        app: gowebapp
    spec:
      containers:
        - name: gowebapp-cont
          image: truebad0ur/gowebapp:v5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: balancer-service
spec:
  selector:
    app: gowebapp
  ports:
    - port: 3333
      targetPort: 8080
  type: LoadBalancer
